### ISSUE TITLE
Resizing is very slow

### ISSUE THREAD

**Issue by bertob** [lainsce/notejot#235]
In the latest version the window is very slow and janky to resize, it can take half a second or more for the window to respond.

**Comment by lainsce** [comment]
Should be fixed now.

**Comment by bertob** [comment]
I just built master, and it's still the same as before here.

**Comment by lainsce** [comment]
Weird, I definitley noticed a improvement by making the code that registers the window size into gschema run under an GLib.Idle and being async...

**Comment by lainsce** [comment]
OK, what I was doing was incorrect. GTK4 or Mutter already autosaves the window's size for me, and I don't need to do it.

Actually fixed this time. :)

**Comment by bertob** [comment]
I can confirm that :raised_hands:
