### ISSUE TITLE
Note saving is unreliable

### ISSUE THREAD

**Issue by aljelly** [lainsce/notejot#35]
Steps to reproduce (clear all previous notes before testing):

1. Open Notejot. Write "1" in the first note.
2. Create 3 more notes, writing "2", "3" and "4" in each new one (so the number corresponds to the order of creation).
3. Using the close button in the header bar, close the notes in this order: note 4, then 3, then 2, then 1.
4. Open Notejot again. Note 4 has lost it's contents and is in a different position.

If you repeat the above but close it in the order of 1, 2, 3, 4, notes 1 and 2 lose their contents and position but 3 and 4 are fine. Similar pattern with 2, 4, 1, 3: notes 2 and 4 are reset.

If you use the order 1, 4, 3, 2, all notes retain their contents and position.

This is when you press the close button on the header bar. If you instead close by right clicking via the header bar and selecting Close and use the order 4, 3, 2, 1, only note 1 keeps it's contents, the others have lost their contents and position.

The Ctrl + Q shortcut isn't affected by this (i.e. you don't lose any notes). Right clicking Notejot on the dock and clicking "Close all" is not affected either.

This is using 1.2.8.

**Comment by lainsce** [comment]
i'll see what is causing this and will fix it for the next release. :+1:

**Comment by lainsce** [comment]
Fixed in 1.3.0, closing~

**Comment by sendittokeith** [comment]
Still happens in latest version as of 4/2019 -- lost another note.  I can no longer trust the app.  It had potential to be the best sticky note app but loss of data is very bad.
