### ISSUE TITLE
Data Loss when working with multiple notes

### ISSUE THREAD

**Issue by arshubham** [lainsce/notejot#43]
[Steps to reproduce](https://youtu.be/seTWbWko2QY)

1. Open two notes and write something. 
2. If you close both of them and open from the slingshot again. No data is lost
3. If one of them is closed and opened from slingshot. A blank note with no window controls is created.
4. On closing both the notes and opening again. Data which was in the note closed in step 3 is lost however title is preserved. (This happened every time I tried earlier however while making the video didn't occur on the first try.)
5. On repeating step three and four on the other note, its data is lost too.

Note: On clicking the header bar in the note with no window controls both notes are closed.

**Comment by lainsce** [comment]
Are you on Loki or a customized pantheon in a newer distro?

Since I believe I fixed this in the upcoming release.

**Comment by arshubham** [comment]
Just saw that appcenter has the v1.3.3. Will compile and check again. 
BTW i am using loki with daily ppa

**Comment by arshubham** [comment]
I am still getting the issue.  Now after getting the blank note with no windows controls, I restarted the app. This time I get the windows controls but can't type anything or move the note (although works again after selecting the other note a few times, but returns to original state after losing focus.).

**Comment by lainsce** [comment]
I meant that on this Friday, I'll release to review a new version (1.3.5) that solves this problem.

**Comment by arshubham** [comment]
I compiled it myself from the master. and tested again

**Comment by lainsce** [comment]
I see what you mean now! I'll see what causes this and fix it.

**Comment by lainsce** [comment]
Fixed in master, will be released on 1.3.6

**Comment by arshubham** [comment]
Still having data loss issue on master (Tested after a reboot). 

[See Video ](https://youtu.be/B7_2owLuJA4)  --> Happens after two tries to reproduce the bug

Not in every time but it happens as:
1. Create 2 notes
2. Close 1 note .
3. Click on the icon from slingshot .
4. Close other note.
5. Open notejot again from slingshot. The first note will be empty but title and color is remembered.
